Freeze meson deps for GraalPy
See https://github.com/diofant/python-gmp/actions/runs/31449225267/job/93649965596

  meson-python: error: Could not execute meson: Traceback (most recent call last):
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/bin/meson", line 8, in <module>
  meson-python: error:     sys.exit(main())
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 322, in main
  meson-python: error:     return run(sys.argv[1:], launcher)
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 312, in run
  meson-python: error:     validate_original_args(args)
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 248, in validate_original_args
  meson-python: error:     import mesonbuild.options
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/lib/python3.12/site-packages/mesonbuild/options.py", line 658, in <module>
  meson-python: error:     UserStringOption('prefix', 'Installation prefix', default_prefix()),
  meson-python: error:   File "/tmp/pip-build-env-3gaeua69/overlay/lib/python3.12/site-packages/mesonbuild/utils/core.py", line 62, in __new__
  meson-python: error:     return super().__new__(cls)
  meson-python: error: TypeError: object.__new__(UserStringOption) is not safe, use UserStringOption.__new__()
  error: subprocess-exited-with-error

(cherry picked from commit 7332c05d19631f15957a2f87c4d3dbaec75efff0)